spring:
  application:
    name: pa-web-api
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: none  
      
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        hbm2ddl.auto: none
        use_sql_comments: false
        max_fetch_depth: 3 
        jdbc.batch_size: 10
        fetch_size: 50 
  datasource:
    url: jdbc:postgresql://localhost:5432/personnal_assistant_invoice_db
    username: postgres
    password: manager
    driver-class-name: org.postgresql.Driver   
    initialization-mode: always